title: Your Name
email: mahdiporjahangiri.dev@gmail.com
description: >-
  Personal website showcasing my projects and blog posts.
baseurl: ""
url: "https://Mahdipoorjahangiri.github.io"
github_username: Mahdipoorjahangiri
linkedin_username: mahdi-poorjahangiri

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  projects:
    output: true
    permalink: /projects/:path/
